In [1]:
import numpy as np

In [6]:
б_x = np.array([[0, 1],
                [1, 0]])

б_x

array([[0, 1],
       [1, 0]])

In [7]:
np.linalg.eig(б_x)

(array([ 1., -1.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [8]:
1 / np.sqrt(2)

0.7071067811865475

In [12]:
a = ((-1 + 0j) + np.sqrt(3.0) *1j) / 2

In [14]:
a**3

(0.9999999999999998+1.1102230246251565e-16j)

In [15]:
8**(1/3)

2.0

In [16]:
a

(-0.5+0.8660254037844386j)

In [17]:
np.linalg.norm(a**3)

0.9999999999999998