In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
A = np.array([[41, -12j], [12j, 34]])
A

array([[41. +0.j, -0.-12.j],
       [ 0.+12.j, 34. +0.j]])

## A

In [3]:
eigvalues, eigvectors = LA.eig(A)
eigvalues, eigvectors

(array([50.+0.j, 25.+0.j]),
 array([[ 0.8+0.j , -0. +0.6j],
        [-0. +0.6j,  0.8+0.j ]]))

In [4]:
D = np.array([[eigvalues[0], 0], [0, eigvalues[1]]])
D

array([[50.+0.j,  0.+0.j],
       [ 0.+0.j, 25.+0.j]])

In [7]:
U = eigvectors
U

array([[ 0.8+0.j , -0. +0.6j],
       [-0. +0.6j,  0.8+0.j ]])

## B

In [8]:
# verify A = U B U^(-1)
U @ D @ LA.inv(U)

array([[41. +0.j,  0.-12.j],
       [ 0.+12.j, 34. +0.j]])